const data = [
	{
		topicName: "Array",
		position: 0,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "Array",
				Problem: "Reverse the array",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/reverse-an-array/0",
			},
			{
				Topic: "Array",
				Problem: "Find the maximum and minimum element in an array",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/find-minimum-and-maximum-element-in-an-array4428/1",
			},
			{
				Topic: "Array",
				Problem: 'Find the "Kth" max and min element of an array ',
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/kth-smallest-element/0",
			},
			{
				Topic: "Array",
				Problem: "Given an array which consists of only 0, 1 and 2. Sort the array without using any sorting algo",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
			},
			{
				Topic: "Array",
				Problem: "Move all the negative elements to one side of the array ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/move-all-negative-elements-to-end1813/1",
			},
			{
				Topic: "Array",
				Problem: "Find the Union and Intersection of the two sorted arrays.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/union-of-two-arrays/0",
			},
			{
				Topic: "Array",
				Problem: "Write a program to cyclically rotate an array by one.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
			},
			{
				Topic: "Array",
				Problem: "find Largest sum contiguous Subarray [V. IMP]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
			},
			{
				Topic: "Array",
				Problem: "Minimise the maximum difference between heights [V.IMP]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
			},
			{
				Topic: "Array",
				Problem: "Minimum no. of Jumps to reach end of an array",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
			},
			{
				Topic: "Array",
				Problem: "find duplicate in an array of N+1 Integers",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/find-the-duplicate-number/",
			},
			{
				Topic: "Array",
				Problem: "Merge 2 sorted arrays without using Extra space.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
			},
			{
				Topic: "Array",
				Problem: "Kadane's Algo [V.V.V.V.V IMP]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
			},
			{
				Topic: "Array",
				Problem: "Merge Intervals",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/merge-intervals/",
			},
			{
				Topic: "Array",
				Problem: "Next Permutation",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/next-permutation/",
			},
			{
				Topic: "Array",
				Problem: "Count Inversion",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
			},
			{
				Topic: "Array",
				Problem: "Best time to buy and Sell stock",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
			},
			{
				Topic: "Array",
				Problem: "find all pairs on integer array whose sum is equal to given number",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
			},
			{
				Topic: "Array",
				Problem: "find common elements In 3 sorted arrays",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
			},
			{
				Topic: "Array",
				Problem: "Rearrange the array in alternating positive and negative items with O(1) extra space",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/array-of-alternate-ve-and-ve-nos1401/1",
			},
			{
				Topic: "Array",
				Problem: "Find if there is any subarray with sum equal to 0",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
			},
			{
				Topic: "Array",
				Problem: "Find factorial of a large number",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
			},
			{
				Topic: "Array",
				Problem: "find maximum product subarray ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
			},
			{
				Topic: "Array",
				Problem: "Find longest consecutive subsequence",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
			},
			{
				Topic: "Array",
				Problem: 'Given an array of size n and a number k, find all elements that appear more than " n/k " times.',
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/majority-element-ii/",
			},
			{
				Topic: "Array",
				Problem: "Maximum profit by buying and selling a share atmost twice",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/",
			},
			{
				Topic: "Array",
				Problem: "Find whether an array is a subset of another array",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
			},
			{
				Topic: "Array",
				Problem: "Find the triplet that sum to a given value",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/triplet-sum-in-array/0",
			},
			{
				Topic: "Array",
				Problem: "Trapping Rain water problem",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/trapping-rain-water/0",
			},
			{
				Topic: "Array",
				Problem: "Chocolate Distribution problem",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0",
			},
			{
				Topic: "Array",
				Problem: "Smallest Subarray with sum greater than a given value",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/minimum-size-subarray-sum/",
			},
		]
	}
]