const data = [
	{
		topicName: "Array",
		position: 0,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "Array",
				Problem: "Reverse the array",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/reverse-an-array/0",
			},
			{
				Topic: "Array",
				Problem: "Find the maximum and minimum element in an array",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/find-minimum-and-maximum-element-in-an-array4428/1",
			},
			{
				Topic: "Array",
				Problem: 'Find the "Kth" max and min element of an array ',
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/kth-smallest-element/0",
			},
			{
				Topic: "Array",
				Problem: "Given an array which consists of only 0, 1 and 2. Sort the array without using any sorting algo",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
			},
			{
				Topic: "Array",
				Problem: "Move all the negative elements to one side of the array ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/move-all-negative-elements-to-end1813/1",
			},
			{
				Topic: "Array",
				Problem: "Find the Union and Intersection of the two sorted arrays.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/union-of-two-arrays/0",
			},
			{
				Topic: "Array",
				Problem: "Write a program to cyclically rotate an array by one.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
			},
			{
				Topic: "Array",
				Problem: "find Largest sum contiguous Subarray [V. IMP]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
			},
			{
				Topic: "Array",
				Problem: "Minimise the maximum difference between heights [V.IMP]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
			},
			{
				Topic: "Array",
				Problem: "Minimum no. of Jumps to reach end of an array",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
			},
			{
				Topic: "Array",
				Problem: "find duplicate in an array of N+1 Integers",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/find-the-duplicate-number/",
			},
			{
				Topic: "Array",
				Problem: "Merge 2 sorted arrays without using Extra space.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
			},
			{
				Topic: "Array",
				Problem: "Kadane's Algo [V.V.V.V.V IMP]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
			},
			{
				Topic: "Array",
				Problem: "Merge Intervals",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/merge-intervals/",
			},
			{
				Topic: "Array",
				Problem: "Next Permutation",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/next-permutation/",
			},
			{
				Topic: "Array",
				Problem: "Count Inversion",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
			},
			{
				Topic: "Array",
				Problem: "Best time to buy and Sell stock",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
			},
			{
				Topic: "Array",
				Problem: "find all pairs on integer array whose sum is equal to given number",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
			},
			{
				Topic: "Array",
				Problem: "find common elements In 3 sorted arrays",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
			},
			{
				Topic: "Array",
				Problem: "Rearrange the array in alternating positive and negative items with O(1) extra space",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/array-of-alternate-ve-and-ve-nos1401/1",
			},
			{
				Topic: "Array",
				Problem: "Find if there is any subarray with sum equal to 0",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
			},
			{
				Topic: "Array",
				Problem: "Find factorial of a large number",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
			},
			{
				Topic: "Array",
				Problem: "find maximum product subarray ",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
			},
			{
				Topic: "Array",
				Problem: "Find longest consecutive subsequence",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
			},
			{
				Topic: "Array",
				Problem: 'Given an array of size n and a number k, find all elements that appear more than " n/k " times.',
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/majority-element-ii/",
			},
			{
				Topic: "Array",
				Problem: "Maximum profit by buying and selling a share atmost twice",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/",
			},
			{
				Topic: "Array",
				Problem: "Find whether an array is a subset of another array",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
			},
			{
				Topic: "Array",
				Problem: "Find the triplet that sum to a given value",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/triplet-sum-in-array/0",
			},
			{
				Topic: "Array",
				Problem: "Trapping Rain water problem",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/trapping-rain-water/0",
			},
			{
				Topic: "Array",
				Problem: "Chocolate Distribution problem",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0",
			},
			{
				Topic: "Array",
				Problem: "Smallest Subarray with sum greater than a given value",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/minimum-size-subarray-sum/",
			},
			{
				Topic: "Array",
				Problem: "Three way partitioning of an array around a given value",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/three-way-partitioning/1",
			},
			{
				Topic: "Array",
				Problem: "Minimum swaps required bring elements less equal K together",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/minimum-swaps-required-to-bring-all-elements-less-than-or-equal-to-k-together/0",
			},
			{
				Topic: "Array",
				Problem: "Minimum no. of operations required to make an array palindrome",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://app.glider.ai/practice/problem/basic-programming/make-array-palindrome/problem",
			},
			{
				Topic: "Array",
				Problem: "Median of 2 sorted arrays of equal size",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/find-the-median0527/1",
			},
			{
				Topic: "Array",
				Problem: "Median of 2 sorted arrays of different size",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/median-of-two-sorted-arrays-of-different-sizes/",
			},
		],
	},
	{
		
			topicName: "Matrix",
			position: 1,
			started: false,
			doneQuestions: 0,
			questions: [
				{
					Topic: "Matrix",
					Problem: "Spiral traversal on a Matrix",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix/0",
				},
				{
					Topic: "Matrix",
					Problem: "Search an element in a matriix",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://leetcode.com/problems/search-a-2d-matrix/",
				},
				{
					Topic: "Matrix",
					Problem: "Find median in a row wise sorted matrix",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1",
				},
				{
					Topic: "Matrix",
					Problem: "Find row with maximum no. of 1's",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1",
				},
				{
					Topic: "Matrix",
					Problem: "Print elements in sorted order using row-column wise sorted matrix",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://practice.geeksforgeeks.org/problems/sorted-matrix/0",
				},
				{
					Topic: "Matrix",
					Problem: "Maximum size rectangle",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://practice.geeksforgeeks.org/problems/max-rectangle/1",
				},
				{
					Topic: "Matrix",
					Problem: "Find a specific pair in matrix",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://www.geeksforgeeks.org/find-a-specific-pair-in-matrix/",
				},
				{
					Topic: "Matrix",
					Problem: "Rotate matrix by 90 degrees",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://www.geeksforgeeks.org/rotate-a-matrix-by-90-degree-in-clockwise-direction-without-using-any-extra-space/",
				},
				{
					Topic: "Matrix",
					Problem: "Kth smallest element in a row-column wise sorted matrix",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://practice.geeksforgeeks.org/problems/kth-element-in-matrix/1",
				},
				{
					Topic: "Matrix",
					Problem: "Common elements in all rows of a given matrix",
					Done: false,
					Bookmark: false,
					Notes: "",
					URL: "https://www.geeksforgeeks.org/common-elements-in-all-rows-of-a-given-matrix/",
				},
			],
	},
	{
		topicName: "String",
		position: 2,
		started: false,
		doneQuestions: 0,
		questions: [
			{
				Topic: "String",
				Problem: "Reverse a String",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/reverse-string/",
			},
			{
				Topic: "String",
				Problem: "Check whether a String is Palindrome or not",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/palindrome-string0817/1",
			},
			{
				Topic: "String",
				Problem: "Find Duplicate characters in a string",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/print-all-the-duplicates-in-the-input-string/",
			},
			{
				Topic: "String",
				Problem: "Why strings are immutable in Java?",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.baeldung.com/java-string-immutable",
			},
			{
				Topic: "String",
				Problem: "Write a Code to check whether one string is a rotation of another",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/a-program-to-check-if-strings-are-rotations-of-each-other/",
			},
			{
				Topic: "String",
				Problem: "Write a Program to check whether a string is a valid shuffle of two strings or not",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.programiz.com/java-programming/examples/check-valid-shuffle-of-strings",
			},
			{
				Topic: "String",
				Problem: "Count and Say problem",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/count-and-say/",
			},
			{
				Topic: "String",
				Problem: "Write a program to find the longest Palindrome in a string.[ Longest palindromic Substring]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/longest-palindrome-in-a-string/0",
			},
			{
				Topic: "String",
				Problem: "Find Longest Recurring Subsequence in String",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/longest-repeating-subsequence/0",
			},
			{
				Topic: "String",
				Problem: "Print all Subsequences of a string.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/print-subsequences-string/",
			},
			{
				Topic: "String",
				Problem: "Print all the permutations of the given string",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
			},
			{
				Topic: "String",
				Problem: "Split the Binary string into two substring with equal 0’s and 1’s",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/split-the-binary-string-into-substrings-with-equal-number-of-0s-and-1s/",
			},
			{
				Topic: "String",
				Problem: "Word Wrap Problem [VERY IMP].",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/word-wrap/0",
			},
			{
				Topic: "String",
				Problem: "EDIT Distance [Very Imp]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/edit-distance3702/1",
			},
			{
				Topic: "String",
				Problem: "Find next greater number with same set of digits. [Very Very IMP]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/next-permutation/0",
			},
			{
				Topic: "String",
				Problem: "Balanced Parenthesis problem.[Imp]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0",
			},
			{
				Topic: "String",
				Problem: "Word break Problem[ Very Imp]",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/word-break/0",
			},
			{
				Topic: "String",
				Problem: "Rabin Karp Algo",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/",
			},
			{
				Topic: "String",
				Problem: "KMP Algo",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/longest-prefix-suffix2527/1",
			},
			{
				Topic: "String",
				Problem: "Convert a Sentence into its equivalent mobile numeric keypad sequence.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/convert-sentence-equivalent-mobile-numeric-keypad-sequence/",
			},
			{
				Topic: "String",
				Problem: "Minimum number of bracket reversals needed to make an expression balanced.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/count-the-reversals/0",
			},
			{
				Topic: "String",
				Problem: "Count All Palindromic Subsequence in a given String.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/count-palindromic-subsequences/1",
			},
			{
				Topic: "String",
				Problem: "Count of number of given string in 2D character array",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/find-count-number-given-string-present-2d-character-array/",
			},
			{
				Topic: "String",
				Problem: "Boyer Moore Algorithm for Pattern Searching.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/boyer-moore-algorithm-for-pattern-searching/",
			},
			{
				Topic: "String",
				Problem: "Longest Common Prefix",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://leetcode.com/problems/longest-common-prefix/",
			},
			{
				Topic: "String",
				Problem: "Number of flips to make binary string alternate",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/min-number-of-flips/0",
			},
			{
				Topic: "String",
				Problem: "Find the first repeated word in string.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/find-first-repeated-word-string/",
			},
			{
				Topic: "String",
				Problem: "Minimum number of swaps for bracket balancing.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/minimum-swaps-for-bracket-balancing/0",
			},
			{
				Topic: "String",
				Problem: "Find the longest common subsequence between two strings.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0",
			},
			{
				Topic: "String",
				Problem: "Program to generate all possible valid IP addresses from given  string.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/program-generate-possible-valid-ip-addresses-given-string/",
			},
			{
				Topic: "String",
				Problem: "Write a program to find the smallest window that contains all characters of string itself.",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/smallest-distant-window/0",
			},
			{
				Topic: "String",
				Problem: "Rearrange characters in a string such that no two adjacent are same",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0",
			},
			{
				Topic: "String",
				Problem: "Minimum characters to be added at front to make string palindrome",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/minimum-characters-added-front-make-string-palindrome/",
			},
			{
				Topic: "String",
				Problem: "Given a sequence of words, print all anagrams together",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/k-anagrams-1/0",
			},
			{
				Topic: "String",
				Problem: "Find the smallest window in a string containing all characters of another string",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string/0",
			},
			{
				Topic: "String",
				Problem: "Recursively remove all adjacent duplicates",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/consecutive-elements/0",
			},
			{
				Topic: "String",
				Problem: "String matching where one string contains wildcard characters",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://practice.geeksforgeeks.org/problems/wildcard-string-matching/0",
			},
			{
				Topic: "String",
				Problem: "Function to find Number of customers who could not get a computer",
				Done: false,
				Bookmark: false,
				Notes: "",
				URL: "https://www.geeksforgeeks.org/function-to-find-number-of-customers-who-could-not-get-a-computer/",
			},
		]
	}
]